[build]
builder = "nixpacks"
buildCommand = "dotnet restore && dotnet publish -c Release -o output"
[deploy]
startCommand = "dotnet output/CoDevelopAPI.dll"
[nixpacks]
providers = ["dotnet"]

[install.apt]
packages = []

[install.nix]
packages = ["dotnet-sdk_8"]